### ISSUE TITLE
File Map and Graph improvements

### ISSUE THREAD

**Issue by iAdramelk** [smelukov/statoscope#17]
File Map and Graph views are cool, but without ability to go to the file in the Details view they are not very useful.

Basically right now I can see in File Map that my bundle includes `underscore`, but there is no easy way to understand why is it included. I need to go to Details, find all `underscore` files bundle, somehow find which if these files was required in my bundle (because underscore or lodash can be imported on per module basis) and then look at their details.

Same with Graph. I can see file's dependencies, but then I want to look at the Retained info, I need to look for this file from scratch in Details.

Also if it is possible to show some additional file info in File Map and Graph it will be very cool. For example Gzip size like it was shown in: https://github.com/th0r/webpack-bundle-analyzer

**Comment by restrry** [comment]
I don't know should I create separate issue or the current one could be used as umbrella. My notice about wrong file size in File Map. ie, for react it shows next:
![2017-04-27_15-44-43](https://cloud.githubusercontent.com/assets/3198181/25486160/8b0481fc-2b60-11e7-806d-357c0ce267f2.png)

`webpack-bundle-analyzer` doesn't use stat, but its own calculating mechanism
https://github.com/th0r/webpack-bundle-analyzer/blob/545c680d0a87920a53acbdf52c8c389dd672d043/src/analyzer.js#L101-L104

probably it worth to switch to `webpack-bundle-analyzer` implementation for File Map?

**Comment by smelukov** [comment]
@restrry I'll investigate it
@iAdramelk, @restrry thanks

**Comment by ocie** [comment]
It looks like to me the size is ignoring the KB/MB. For example, I have a library that shows up as 980 bytes in the file map, but in the file listing under "home", it is listed as 980 KB.

**Comment by smelukov** [comment]
Now we have a brand new analyzer in this repo, please check this out 😀

**Comment by iAdramelk** [comment]
Cool! Will give it a go!
