### ISSUE TITLE
Show which chunk file \ module belongs to

### ISSUE THREAD

**Issue by VsevolodTrofimov** [smelukov/statoscope#20]
This can be shown either by coloring nodes in dependecy graph or in the details tab

If you are intrested I will work on PR with this (assuming it's possible)

**Comment by smelukov** [comment]
Hi! Can you describe any use case in which this feature will be useful?

**Comment by VsevolodTrofimov** [comment]
Sure,
When async chuks are being used for code splitting webpack tends to act very curious (in my case putting shared async dependencies in entrypoint chunk), other people struggle with code duplication while using them, it varies depending on webpack version. And this behaviour is poorly documentend. 

This feature will make debugging this cases way easier and might provide useful insights on how to adjust code splitting for better preformance, as it will be clearer how you chunks depend on each other and why files got to N'th chunk.

**Comment by smelukov** [comment]
Now we have a brand new analyzer in this repo, please check this out 😀
