### ISSUE TITLE
Does not support webpack 4

### ISSUE THREAD

**Issue by StepinPV** [smelukov/statoscope#25]
Hi! When i try to build a project with using webpack 4, build fails with an exception:

emitting/Users/pvstepin/dev/avito-mobile-site/node_modules/webpack/lib/Chunk.js:446
throw new Error("Chunk.parents: Use ChunkGroup.getParents() instead");
^

Error: Chunk.parents: Use ChunkGroup.getParents() instead
at Chunk.get (/Users/pvstepin/dev/avito-mobile-site/node_modules/webpack/lib/Chunk.js:446:9)
at /Users/pvstepin/dev/avito-mobile-site/node_modules/webpack-runtime-analyzer/src/plugin/index.js:266:32

**Comment by smelukov** [comment]
Now we have a brand new analyzer in this repo, please check this out 😀
