### ISSUE TITLE
Alpha pre-release to test

### ISSUE THREAD

**Issue by LucaColonnello** [smelukov/statoscope#26]
Hello!!! 👋
I've been looking for a similar tool from months now, when I found this I was soooo happy!
Specifically the Details view, telling you each file size with his deps and their weight.

Unfortunately it does not yet work with Webpack v4, but I can see you're working on it, which is great!

Is it possible to have a `@next` release to test it on my project?
I'd love to try it out, even if it's not perfect!

Many thanks for the effort on sharing this tool! :)

**Comment by smelukov** [comment]
Hello! Sure, I've published `webpack-runtime-analyzer@next` package.
Thanks for your feedback!

**Comment by LucaColonnello** [comment]
Amazing, will try it ASAP, thanks for being so reactive on this! :)

**Comment by LucaColonnello** [comment]
I tried it this morning in standalone mode and nothing showed unfortunately. I have a multi-compiler webpack config, using webpack 4.
Any clue on what this could be?

**Comment by smelukov** [comment]
Now we have a brand new analyzer in this repo, please check this out 😀
