### ISSUE TITLE
Error during stats analysis

### ISSUE THREAD

**Issue by budarin** [smelukov/statoscope#29]
![image](https://user-images.githubusercontent.com/8055157/101023028-3f110500-3583-11eb-8c07-5472d9b6e2f2.png)

**Comment by smelukov** [comment]
Can you provide a page and stats example to reproduce the error?

**Comment by budarin** [comment]
How canI share stats.json? It's quite big

**Comment by smelukov** [comment]
You can zip it and attach to this issue
Also you can create a stats without sources, just disable it in your webpack config:
stats: { all: true, source: false }

**Comment by budarin** [comment]
[stats.json.zip](https://github.com/smelukov/statoscope/files/5639331/stats.json.zip)

**Comment by smelukov** [comment]
Seems like all is ok (I can't reproduce it) 🤔
Which browser (Name + version) do you use?

**Comment by budarin** [comment]
Chrome 86.0.4240.198 Windows
The same is on Mac Book

**Comment by smelukov** [comment]
@budarin can you check now?

**Comment by budarin** [comment]
What does it means `deopts` ?
![image](https://user-images.githubusercontent.com/8055157/102018001-8bc2c000-3d7b-11eb-9f90-57c639af9c6c.png)

**Comment by budarin** [comment]
the error is still present

class l {
        constructor(e) {
            this.readers = e.map(e=>{
                const t = new s(e);
                return t.eventProgress.on((e,{total: t, loaded: n, chunkSize: r})=>{
                    this.loadedBytes += r,
                    this.eventProgress.emit(this, {
                        total: this.totalBytes,
                        loaded: this.loadedBytes
                    })
                }
                ),
                t
            }
            ),
            this.totalBytes = e.reduce((e,t)=>e + t.size, 0),
            this.loadedBytes = 0,
            this.eventProgress = new o.a
        }
e is FileList so it doesn't have map property

**Comment by smelukov** [comment]
> What does it means `deopts` ?

Please, ask the question on [Discussions](https://github.com/smelukov/statoscope/discussions/33) page

**Comment by smelukov** [comment]
> e is FileList so it doesn't have map property

I've updated https://statoscope.tech/ to normalize FileList to array

**Comment by budarin** [comment]
Ок

**Comment by smelukov** [comment]
Is the problem still actual?
