### ISSUE TITLE
Start page should have the information about the stats flags

### ISSUE THREAD

**Issue by victor-homyakov** [smelukov/statoscope#48]
When my project has custom configuration and build scripts, I simply cannot  run `webpack --json > stats.json`. I just need to know which flags to enable. But it's hard to find this information (btw it's here: https://github.com/smelukov/statoscope/tree/master/packages/ui-webpack#which-stats-flags-statoscope-use).

I'd like to see a short list of needed stats flags (or a link to the doc) right on the start page https://statoscope.tech/

**Comment by smelukov** [comment]
Done.
Thanks for the issue!

<img src="https://user-images.githubusercontent.com/6654581/111664760-28857580-8823-11eb-85bc-e5ef5ac1f080.png" width="400">
