### ISSUE TITLE
Statoscope plugin for Workbox

### ISSUE THREAD

**Issue by budarin** [smelukov/statoscope#49]
Here is the issue to the Workbox project https://github.com/GoogleChrome/workbox/issues/2785

is the Statoscope compatible with child compilations?

Demo [project](https://github.com/budarin/statoscope-for-workbox/tree/master)

**Comment by smelukov** [comment]
Now statoscope ignores child compilations
I'll add support of child compilations

**Comment by smelukov** [comment]
Closed by v4.0.0
